
name: Update Homicide Data Hourly with Gmail Alerts

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install node-fetch@2

      - name: Run Update Script
        run: |
          echo "Running update-homicide-data.mjs"
          node --experimental-modules update-homicide-data.mjs
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0

      - name: Commit and Push Updated JSON
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "bot@example.com"
          git add public/data/homicide.json
          git commit -m "Hourly homicide data update" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}

  notify-on-failure:
    if: failure()
    needs: update
    runs-on: ubuntu-latest
    steps:
      - name: Send Gmail Alert
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Action Failed - Homicide Data Update"
          to: ${{ secrets.ALERT_EMAIL }}
          from: "GitHub Bot <${{ secrets.EMAIL_USERNAME }}>"
          body: |
            The GitHub Action to update homicide data failed.
            Please check your Actions tab for details.
